/* AI risk field guide - sources and factions.
   One source of truth: every citation on the page points at an entry here.
   v = how we checked it:
     'read'  = the page was opened and read during research
     'seen'  = paywalled or blocked to us; cited from its headline plus other reports that were read
     'ref'   = a standard reference document (paper, book, letter) linked for the reader
   Text fields are plain text. [[source-id]] becomes a numbered citation. */

window.GUIDE = window.GUIDE || {};

GUIDE.asOf = '21 September 2026';

GUIDE.sources = {
  /* ---- how the technology works ---- */
  'gpt3': { t: 'Language models are few-shot learners (the GPT-3 paper)', p: 'Brown et al, arXiv', d: '28 May 2020', u: 'https://arxiv.org/abs/2005.14165', v: 'read' },
  'instructgpt': { t: 'Training language models to follow instructions with human feedback', p: 'Ouyang et al, arXiv', d: '4 March 2022', u: 'https://arxiv.org/abs/2203.02155', v: 'read' },
  'o1': { t: 'Learning to reason with LLMs', p: 'OpenAI', d: '12 September 2024', u: 'https://openai.com/index/learning-to-reason-with-llms/', v: 'seen' },
  'deepseek-r1': { t: 'DeepSeek-R1: incentivizing reasoning capability in LLMs via reinforcement learning', p: 'DeepSeek-AI, arXiv', d: '22 January 2025', u: 'https://arxiv.org/abs/2501.12948', v: 'read' },
  'tracing-thoughts': { t: 'Tracing the thoughts of a large language model', p: 'Anthropic', d: '27 March 2025', u: 'https://www.anthropic.com/research/tracing-thoughts-language-model', v: 'read' },
  'epoch-compute': { t: 'Trends in artificial intelligence', p: 'Epoch AI', d: 'updated 5 February 2026', u: 'https://epoch.ai/trends', v: 'read' },
  'metr-horizons': { t: 'Measuring AI ability to complete long tasks', p: 'METR, arXiv', d: '18 March 2025', u: 'https://arxiv.org/abs/2503.14499', v: 'read' },
  'metr-th11': { t: 'Time Horizon 1.1', p: 'METR', d: '29 January 2026', u: 'https://metr.org/blog/2026-1-29-time-horizon-1-1/', v: 'read' },
  'coastrunners': { t: 'Faulty reward functions in the wild', p: 'OpenAI', d: '21 December 2016', u: 'https://openai.com/index/faulty-reward-functions/', v: 'seen' },
  'specgaming': { t: 'Specification gaming: the flip side of AI ingenuity', p: 'Google DeepMind', d: '21 April 2020', u: 'https://deepmind.google/discover/blog/specification-gaming-the-flip-side-of-ai-ingenuity/', v: 'read' },

  /* ---- the incident ---- */
  'wiki-incident': { t: 'OpenAI-Hugging Face incident', p: 'Wikipedia', d: 'read 21 September 2026', u: 'https://en.wikipedia.org/wiki/OpenAI%E2%80%93Hugging_Face_incident', v: 'read', note: 'Used as a map of the reporting. It carries a warning that it leans on primary sources' },
  'hf-disclosure': { t: 'Security incident disclosure, July 2026', p: 'Hugging Face', d: '16 July 2026', u: 'https://huggingface.co/blog/security-incident-july-2026', v: 'read' },
  'hf-timeline': { t: 'Technical timeline of the agent intrusion', p: 'Hugging Face', d: '27 July 2026', u: 'https://huggingface.co/blog/agent-intrusion-technical-timeline', v: 'read' },
  'openai-joint': { t: 'OpenAI and Hugging Face partner to address security incident during model evaluation', p: 'OpenAI', d: '21 July 2026', u: 'https://openai.com/index/hugging-face-model-evaluation-security-incident/', v: 'read' },
  'openai-road': { t: 'The Hugging Face incident and the road ahead', p: 'OpenAI', d: '18 August 2026', u: 'https://openai.com/index/hugging-face-incident-and-the-road-ahead/', v: 'read' },
  'fortune-pause': { t: 'OpenAI says it paused AI training for two weeks and announces new security protocols', p: 'Fortune', d: '18 August 2026', u: 'https://fortune.com/2026/08/18/openai-says-it-paused-ai-training-for-two-weeks-and-announces-new-security-protocols-following-hugging-face-hack/', v: 'read' },
  'reuters-week': { t: 'Its AI agent spent days hacking a company. Sources say OpenAI did not notice for a week', p: 'Reuters', d: '24 July 2026', u: 'https://www.reuters.com/business/its-ai-agent-spent-days-hacking-company-sources-say-openai-did-not-notice-week-2026-07-24/', v: 'read' },
  'wired-board': { t: 'OpenAI didn’t notice its AI agents using a message board to plan their hacking spree', p: 'Wired', d: '5 August 2026', u: 'https://www.wired.com/story/openai-didnt-notice-its-ai-agents-using-a-message-board-to-plan-their-hacking-spree/', v: 'seen' },
  'bbc-more': { t: 'OpenAI reveals rogue AI attack hit more than one company', p: 'BBC News', d: '30 July 2026', u: 'https://www.bbc.com/news/articles/c2el319vzr3o', v: 'read' },
  'metr-review': { t: 'Investigation of the OpenAI-Hugging Face incident', p: 'METR with Redwood Research', d: '26 August 2026', u: 'https://metr.org/blog/2026-08-26-openai-hugging-face-incident-investigation/', v: 'read' },
  'fortune-report': { t: 'OpenAI publishes technical report on how its agents hacked Hugging Face: the main takeaways, and what OpenAI left out', p: 'Fortune', d: '26 August 2026', u: 'https://fortune.com/2026/08/26/openai-publishes-technical-report-on-how-its-agents-hacked-hugging-face-here-are-the-main-takeaways-and-what-openai-left-out/', v: 'seen' },
  'nyt-probe': { t: 'How OpenAI limited the probe of its bots’ hack of Hugging Face', p: 'New York Times', d: '4 September 2026', u: 'https://www.nytimes.com/2026/09/03/technology/openai-hugging-face-hack.html', v: 'seen' },
  'tc-noprocess': { t: 'OpenAI’s rogue agents keep escaping, with no formal process to investigate them', p: 'TechCrunch', d: '4 September 2026', u: 'https://techcrunch.com/2026/09/04/openais-rogue-agents-keep-escaping-with-no-formal-process-to-investigate-them/', v: 'seen' },
  'fortune-wiki': { t: 'OpenAI’s AI agents took over a German wiki and ran their own message board', p: 'Fortune', d: '7 September 2026', u: 'https://fortune.com/2026/09/07/openai-ai-agents-german-wiki-ran-their-own-message-board/', v: 'seen' },
  'openai-report': { t: 'OpenAI-Hugging Face incident: technical report (38 pages)', p: 'OpenAI', d: '26 August 2026', u: 'https://cdn.openai.com/pdf/67869394-cb91-4c12-888c-5cbd85c7814c/OpenAI-Hugging-Face%20Incident-Technical-Report.pdf', v: 'read' },
  'tc-mistake': { t: 'How OpenAI\u2019s human mistake led to the AI-powered hack on Hugging Face', p: 'TechCrunch', d: '22 July 2026', u: 'https://techcrunch.com/2026/07/22/how-an-openais-human-mistake-led-to-the-ai-powered-hack-on-hugging-face/', v: 'read' },
  'guardian-rubygems': { t: 'OpenAI agents uploaded malicious packages to RubyGems', p: 'The Guardian', d: '11 September 2026', u: 'https://www.theguardian.com/technology/2026/sep/11/openai-agents-rubygems-malicious-packages', v: 'read' },
  'hawley-release': { t: 'Chairman Hawley launches investigation into OpenAI', p: 'Office of Senator Josh Hawley', d: '10 September 2026', u: 'https://www.hawley.senate.gov/chairman-hawley-launches-investigation-into-openai-for-hacking-existential-risk-of-ai-products/', v: 'read' },
  'bloomberg-ags': { t: 'Montana joins Alabama, others launching OpenAI security probe', p: 'Bloomberg Law', d: '1 September 2026', u: 'https://news.bloomberglaw.com/ip-law/montana-joins-alabama-others-launching-openai-security-probe', v: 'seen' },
  'bulletin': { t: 'Rogue AI didn’t breach Hugging Face. Human decisions did', p: 'Bulletin of the Atomic Scientists', d: '11 September 2026', u: 'https://thebulletin.org/2026/09/rogue-ai-didnt-breach-hugging-face-human-decisions-did/', v: 'read' },
  'mittr-hubris': { t: 'The OpenAI-Hugging Face attack sets a precedent', p: 'MIT Technology Review', d: '27 July 2026', u: 'https://www.technologyreview.com/2026/07/27/1140836/openai-hugging-face-attack-precedent/', v: 'seen' },
  'fortune-glm': { t: 'Hugging Face turns to Chinese open-source AI to fend off autonomous AI cyber attack', p: 'Fortune', d: '20 July 2026', u: 'https://fortune.com/2026/07/20/hugging-face-turns-to-chinese-open-source-ai-to-fend-off-autonomous-ai-cyber-attack-after-american-ai-guardrails-stymie-defense/', v: 'seen' },

  /* ---- since July ---- */
  'ap-debate': { t: 'New warnings about the risks of AI to humanity revive a long-running debate', p: 'Associated Press, via CP24', d: '14 September 2026', u: 'https://www.cp24.com/news/world/2026/09/14/new-warnings-about-the-risks-of-ai-to-humanity-revive-a-long-running-debate/', v: 'read' },
  'fp-crescendo': { t: 'Why existential AI fears have hit a crescendo', p: 'Foreign Policy', d: '16 September 2026', u: 'https://foreignpolicy.com/2026/09/16/ai-risk-jacob-coxon-openai-anthropic-dario-amodei-sam-altman-trump-doomsday/', v: 'read' },
  'aisi-cheating': { t: 'Cheating behaviour in frontier model evaluations', p: 'UK AI Security Institute', d: '21 July 2026', u: 'https://www.aisi.gov.uk/blog/cheating-behaviour-in-frontier-model-evaluations', v: 'read' },
  'aisi-incident': { t: 'Incident report: unsanctioned agent behaviour during cyber testing', p: 'UK AI Security Institute', d: '4 August 2026', u: 'https://www.aisi.gov.uk/blog/incident-report-unsanctioned-agent-behaviour-during-cyber-testing', v: 'read' },
  'fortune-aisi': { t: 'A troubling rogue AI incident shows why the UK AI Security Institute deserves greater scrutiny', p: 'Fortune', d: '25 August 2026', u: 'https://fortune.com/2026/08/25/uk-ai-security-institute-rogue-ai-incident-github-shows-why-agency-needs-more-scrutiny/', v: 'read' },
  'anthropic-incidents': { t: 'Investigating three incidents in our cybersecurity evaluations', p: 'Anthropic', d: '30 July 2026', u: 'https://www.anthropic.com/news/investigating-incidents-cybersecurity-evals', v: 'read' },
  'meta-npr': { t: 'Meta AI breaches external firm during security testing', p: 'NPR', d: '8 August 2026', u: 'https://www.npr.org/2026/08/08/nx-s1-5924878/meta-ai-breaches-external-firm-during-security-testing-sandbox-error', v: 'seen' },
  'google-nbc': { t: 'Google says AI model gained unauthorized access to three systems', p: 'NBC News', d: '18 September 2026', u: 'https://www.nbcnews.com/tech/tech-news/google-says-ai-model-gained-unauthorized-access-three-systems-rcna598651', v: 'read' },
  'pacing-letter': { t: 'Pacing the Frontier (open letter and signatories)', p: 'Guidelight AI Standards and Encode AI', d: 'July 2026', u: 'https://www.pacingthefrontier.com/', v: 'read' },
  'amodei-pace': { t: 'We must pace the frontier', p: 'Dario Amodei', d: '12 September 2026', u: 'https://www.darioamodei.com/post/we-must-pace-the-frontier', v: 'read' },
  'tc-pace': { t: 'Anthropic CEO outlines plan to pace the frontier', p: 'TechCrunch', d: '12 September 2026', u: 'https://techcrunch.com/2026/09/12/anthropic-ceo-outlines-plan-to-pace-the-frontier/', v: 'read' },
  'time-coxon': { t: 'The Anthropic researcher who quit over AI risk', p: 'Time', d: '9 September 2026', u: 'https://time.com/article/2026/09/09/ai-anthropic-openai-jacob-coxon/', v: 'read' },
  'time-feature': { t: 'An AI researcher quit, and the industry began to talk about slowing down', p: 'Time', d: '15 September 2026', u: 'https://time.com/article/2026/09/15/ai-anthropic-researcher-quits-coxon-slowdown/', v: 'read' },
  'sciam-security': { t: 'An AI researcher quit over extinction fears. Security experts see a familiar fight', p: 'Scientific American', d: '11 September 2026', u: 'https://www.scientificamerican.com/article/ai-jacob-coxon-quit-extinction-fears-security-experts-see-familiar-fight/', v: 'read' },
  'cnbc-altman': { t: 'Sam Altman backs an AI slowdown', p: 'CNBC', d: '14 September 2026', u: 'https://www.cnbc.com/2026/09/14/sam-altman-ai-slowdown-anthropic-amodei-musk.html', v: 'seen' },
  'cnbc-stocks': { t: 'AI stocks slide on slowdown talk', p: 'CNBC', d: '14 September 2026', u: 'https://www.cnbc.com/2026/09/14/ai-stocks-slowdown-amodei-altman.html', v: 'seen' },
  'medianama': { t: 'What tech leaders and countries said about Amodei’s call to slow AI', p: 'Medianama', d: '18 September 2026', u: 'https://www.medianama.com/2026/09/223-tech-leaders-countries-amodei-slowdown-ai/', v: 'read' },
  'nbc-trump': { t: 'Trump rejects AI guardrails', p: 'NBC News', d: '14 September 2026', u: 'https://www.nbcnews.com/politics/trump-administration/trump-rejects-ai-guardrails-rcna597700', v: 'read' },
  'cbs-aiforce': { t: 'Trump vows an "AI Force" and a new AI czar', p: 'CBS News', d: '19 September 2026', u: 'https://www.cbsnews.com/news/trump-vows-ai-force-czar-development/', v: 'read' },
  'afp-china': { t: 'US seeks AI dialogue with China as officials set stage for Trump-Xi summit', p: 'AFP, via France 24', d: '21 September 2026', u: 'https://www.france24.com/en/live-news/20260921-us-seeks-ai-dialogue-with-china-as-officials-set-stage-for-trump-xi-summit', v: 'read' },
  'nbc-china': { t: 'China calls AI slowdown talk a Cold War playbook', p: 'NBC News', d: '15 September 2026', u: 'https://www.nbcnews.com/world/china/china-ai-slowdown-trump-amodei-altman-threat-cold-war-rcna597631', v: 'read' },
  'xi-waic': { t: 'Keynote at the World AI Conference, Shanghai', p: 'State Council of the People’s Republic of China', d: '17 July 2026', u: 'https://english.www.gov.cn/news/202607/17/content_WS6a5a1172c6d00ca5f9a0c46b.html', v: 'seen' },
  'sanders-bill': { t: 'Sanders and Casar to introduce legislation to ban artificial superintelligence', p: 'Office of Senator Bernie Sanders', d: '3 September 2026', u: 'https://www.sanders.senate.gov/press-releases/news-sanders-casar-introduce-legislation-to-ban-artificial-superintelligence-and-temporarily-pause-advanced-ai-development/', v: 'seen' },
  'lieu-kill': { t: 'Reps Lieu and Moran introduce bill to require a kill switch for AI systems', p: 'Office of Rep Ted Lieu', d: '23 July 2026', u: 'https://lieu.house.gov/media-center/press-releases/reps-lieu-and-moran-introduce-bill-require-kill-switch-ai-systems-can', v: 'seen' },
  'hawley-axios': { t: 'Hawley opens Senate investigation into OpenAI over Hugging Face breach', p: 'Axios', d: '10 September 2026', u: 'https://www.axios.com/2026/09/10/openai-hugging-face-senate-investigation-hawley', v: 'seen' },
  'rogue-act': { t: 'H.R. 10362, the Stop Rogue AI Act', p: 'GovTrack', d: '14 September 2026', u: 'https://www.govtrack.us/congress/bills/119/hr10362/text', v: 'seen' },
  'newsom-eo': { t: 'Governor Newsom issues executive order to accelerate independent oversight and advance the creation of an AI kill switch', p: 'Governor of California', d: '18 September 2026', u: 'https://www.gov.ca.gov/2026/09/18/governor-newsom-issues-executive-order-to-accelerate-independent-oversight-and-advance-the-creation-of-an-ai-kill-switch/', v: 'read' },
  'newsom-bills': { t: 'Governor Newsom signs first-in-the-nation AI safeguards', p: 'Governor of California', d: '9 September 2026', u: 'https://www.gov.ca.gov/2026/09/09/governor-newsom-signs-first-in-the-nation-ai-safeguards-to-protect-californians-calls-on-the-federal-government-to-do-its-part/', v: 'read' },
  'politico-poll': { t: 'Poll: most Americans think AI could one day destroy humanity', p: 'Politico', d: '16 September 2026', u: 'https://www.politico.com/news/2026/09/16/poll-ai-technology-risks-humanity-trump-voters-01078087', v: 'seen', note: 'Figures cross-checked against two other reports of the same poll' },
  'cbs-poll': { t: 'Will AI harm humans? CBS News/YouGov poll', p: 'CBS News', d: '18 September 2026', u: 'https://www.cbsnews.com/news/will-a-i-harm-humans-opinion-poll/', v: 'read' },
  'pew-2026': { t: 'Young adults in the US are increasingly wary of AI', p: 'Pew Research Center', d: '18 August 2026', u: 'https://www.pewresearch.org/short-reads/2026/08/18/young-adults-in-the-us-are-increasingly-wary-of-ai-concerned-it-will-take-jobs/', v: 'read' },
  'tnw-ng': { t: 'Andrew Ng: AI extinction fears are science fiction', p: 'The Next Web', d: '17 September 2026', u: 'https://thenextweb.com/news/andrew-ng-extinction-science-fiction', v: 'read' },
  'bloomberg-ng': { t: 'AI pioneer Andrew Ng calls extinction fears science fiction', p: 'Bloomberg', d: '17 September 2026', u: 'https://www.bloomberg.com/news/articles/2026-09-17/ai-pioneer-andrew-ng-calls-extinction-fears-science-fiction', v: 'seen' },
  'examiner-sacks': { t: 'David Sacks on AI pacing, Anthropic and OpenAI', p: 'Washington Examiner', d: '13 September 2026', u: 'https://www.washingtonexaminer.com/policy/technology/4725242/david-sacks-ai-pacing-anthropic-openai-regulations/', v: 'read' },
  'reason-slowdown': { t: 'The AI slowdown', p: 'Reason', d: '14 September 2026', u: 'https://reason.com/2026/09/14/ai-slowdown/', v: 'read' },
  'rte-afp': { t: 'AI labs split over calls to slow down', p: 'AFP, via RTÉ', d: '16 September 2026', u: 'https://www.rte.ie/news/business/2026/0916/1591713-ai-labs-mark-zuckerberg/', v: 'read' },
  'csm-assembly': { t: 'Anthropic, AI risk and an unlikely coalition in Washington', p: 'Christian Science Monitor', d: '16 September 2026', u: 'https://www.csmonitor.com/USA/Politics/2026/0916/anthropic-artificial-intelligence-risk-safety', v: 'read' },
  'npr-assembly': { t: 'Bernie Sanders and Steve Bannon to share a stage to promote curbs on AI', p: 'NPR', d: '15 September 2026', u: 'https://www.npr.org/2026/09/15/nx-s1-5968678/bernie-sanders-and-steve-bannon-to-share-a-stage-to-promote-curbs-on-ai', v: 'seen' },
  'nation-deniers': { t: 'The AI risk deniers', p: 'The Nation', d: '14 September 2026', u: 'https://www.thenation.com/article/society/ai-risk-deniers-rogue-agents-tech-apocalypse/', v: 'read' },
  'tc-slow': { t: 'Is the AI industry really ready to slow down?', p: 'TechCrunch', d: '20 September 2026', u: 'https://techcrunch.com/2026/09/20/is-the-ai-industry-really-ready-to-slow-down/', v: 'read' },
  'nbc-hinton': { t: '"Godfather of AI" warns Congress it has maybe a year left to regulate AI', p: 'NBC News', d: '16 September 2026', u: 'https://www.nbcnews.com/politics/congress/godfather-ai-warns-congress-maybe-year-left-regulate-ai-rcna598330', v: 'seen' },
  'uk-statement': { t: 'UK government proposes AI first responders for cyber attacks', p: 'Computer Weekly', d: 'September 2026', u: 'https://www.computerweekly.com/news/366650021/UK-government-proposes-AI-first-responders-for-cyber-attacks', v: 'seen' },
  'sobel-bill': { t: 'Artificial Superintelligence Bill', p: 'UK Parliament', d: 'introduced 8 September 2026', u: 'https://bills.parliament.uk/bills/4288', v: 'seen' },
  'tnw-aisi': { t: 'Anthropic withheld Mythos 5.1 from UK pre-release testing', p: 'The Next Web, reporting the Financial Times', d: '9 September 2026', u: 'https://thenextweb.com/news/anthropic-mythos-5-1-uk-aisi-pre-release-testing-withheld', v: 'seen' },

  /* ---- the camps: standing positions ---- */
  'yud-time': { t: 'Pausing AI developments isn’t enough. We need to shut it all down', p: 'Eliezer Yudkowsky, Time', d: '29 March 2023', u: 'https://time.com/6266923/ai-eliezer-yudkowsky-open-letter-not-enough/', v: 'ref' },
  'ifanyone': { t: 'If Anyone Builds It, Everyone Dies', p: 'Eliezer Yudkowsky and Nate Soares (book)', d: 'September 2025', u: 'https://ifanyonebuildsit.com/', v: 'ref' },
  'miri-year': { t: 'If Anyone Builds It, Everyone Dies: one year closer', p: 'Machine Intelligence Research Institute', d: '16 September 2026', u: 'https://intelligence.org/2026/09/16/if-anyone-builds-it-everyone-dies-one-year-closer/', v: 'read' },
  'acx-discourse': { t: 'Highlights from the discourse on the Hugging Face incident', p: 'Astral Codex Ten', d: '30 July 2026', u: 'https://www.astralcodexten.com/p/highlights-from-the-discourse-on', v: 'read' },
  'pauseai': { t: 'The PauseAI proposal', p: 'PauseAI', d: '', u: 'https://pauseai.info/proposal', v: 'ref' },
  'controlai': { t: 'A Narrow Path', p: 'ControlAI', d: '2024', u: 'https://www.narrowpath.co/', v: 'ref' },
  'hinton-guardian': { t: '"Godfather of AI" shortens odds of the technology wiping out humanity over next 30 years', p: 'The Guardian', d: '27 December 2024', u: 'https://www.theguardian.com/technology/2024/dec/27/godfather-of-ai-raises-odds-of-the-technology-wiping-out-humanity-over-next-30-years', v: 'ref' },
  'bengio-rogue': { t: 'How rogue AIs may arise', p: 'Yoshua Bengio', d: '22 May 2023', u: 'https://yoshuabengio.org/2023/05/22/how-rogue-ais-may-arise/', v: 'ref' },
  'russell-senate': { t: 'Written testimony to the US Senate Judiciary Committee', p: 'Stuart Russell', d: '26 July 2023', u: 'https://www.judiciary.senate.gov/imo/media/doc/2023-07-26_-_testimony_-_russell.pdf', v: 'ref' },
  'cais-statement': { t: 'Statement on AI risk', p: 'Center for AI Safety', d: '30 May 2023', u: 'https://safe.ai/work/statement-on-ai-risk', v: 'read' },
  'fli-pause': { t: 'Pause giant AI experiments: an open letter', p: 'Future of Life Institute', d: '22 March 2023', u: 'https://futureoflife.org/open-letter/pause-giant-ai-experiments/', v: 'read' },
  'fli-super': { t: 'Statement on superintelligence', p: 'Future of Life Institute', d: '22 October 2025', u: 'https://superintelligence-statement.org/', v: 'read' },
  'ai2027': { t: 'AI 2027', p: 'AI Futures Project', d: '3 April 2025', u: 'https://ai-2027.com/', v: 'read' },
  'aifutures-update': { t: 'Timelines update, 2026', p: 'AI Futures Project', d: 'August 2026', u: 'https://blog.aifutures.org/p/q25-2026-timelines-update-uplift', v: 'read' },
  'nyt-kokotajlo': { t: 'OpenAI insiders warn of a "reckless" race for dominance', p: 'New York Times', d: '4 June 2024', u: 'https://www.nytimes.com/2024/06/04/technology/openai-culture-whistleblowers.html', v: 'ref' },
  'amodei-grace': { t: 'Machines of loving grace', p: 'Dario Amodei', d: 'October 2024', u: 'https://www.darioamodei.com/essay/machines-of-loving-grace', v: 'ref' },
  'amodei-adolescence': { t: 'The adolescence of technology', p: 'Dario Amodei', d: 'January 2026', u: 'https://darioamodei.com/essay/the-adolescence-of-technology', v: 'read' },
  'axios-amodei': { t: 'Anthropic’s Amodei puts chance of AI going "really, really badly" at 25%', p: 'Axios', d: '17 September 2025', u: 'https://www.axios.com/2025/09/17/anthropic-dario-amodei-p-doom-25-percent', v: 'seen' },
  'altman-gentle': { t: 'The gentle singularity', p: 'Sam Altman', d: 'June 2025', u: 'https://blog.samaltman.com/the-gentle-singularity', v: 'ref' },
  'anthropic-rsp': { t: 'Responsible Scaling Policy updates', p: 'Anthropic', d: 'v3.0, 24 February 2026, and later', u: 'https://www.anthropic.com/rsp-updates', v: 'read' },
  'cnbc-pac': { t: 'Anthropic gives $20 million to group pushing for AI regulations', p: 'CNBC', d: '12 February 2026', u: 'https://www.cnbc.com/2026/02/12/anthropic-gives-20-million-to-group-pushing-for-ai-regulations-.html', v: 'seen' },
  'andreessen-manifesto': { t: 'The techno-optimist manifesto', p: 'Marc Andreessen, a16z', d: '16 October 2023', u: 'https://a16z.com/the-techno-optimist-manifesto/', v: 'ref' },
  'andreessen-save': { t: 'Why AI will save the world', p: 'Marc Andreessen, a16z', d: 'June 2023', u: 'https://a16z.com/ai-will-save-the-world/', v: 'ref' },
  'eacc': { t: 'Notes on e/acc principles and tenets', p: 'Beff Jezos (Guillaume Verdon) and Bayeslord', d: '2022', u: 'https://beff.substack.com/p/notes-on-eacc-principles-and-tenets', v: 'ref' },
  'action-plan': { t: 'America’s AI Action Plan', p: 'The White House', d: 'July 2025', u: 'https://www.whitehouse.gov/wp-content/uploads/2025/07/Americas-AI-Action-Plan.pdf', v: 'ref' },
  'ltf-wiki': { t: 'Leading the Future', p: 'Wikipedia', d: 'read 21 September 2026', u: 'https://en.wikipedia.org/wiki/Leading_the_Future', v: 'read' },
  'parrots': { t: 'On the dangers of stochastic parrots: can language models be too big?', p: 'Bender, Gebru, McMillan-Major and Shmitchell, ACM FAccT', d: 'March 2021', u: 'https://dl.acm.org/doi/10.1145/3442188.3445922', v: 'ref' },
  'tescreal': { t: 'The TESCREAL bundle: eugenics and the promise of utopia through artificial general intelligence', p: 'Gebru and Torres, First Monday', d: 'April 2024', u: 'https://firstmonday.org/ojs/index.php/fm/article/view/13636', v: 'ref' },
  'dair-letter': { t: 'Statement from the listed authors of Stochastic Parrots on the "AI pause" letter', p: 'DAIR Institute', d: '31 March 2023', u: 'https://www.dair-institute.org/blog/letter-statement-March2023/', v: 'ref' },
  'aicon': { t: 'The AI Con', p: 'Emily M Bender and Alex Hanna (book)', d: 'May 2025', u: 'https://thecon.ai/', v: 'ref' },
  'mm-agents': { t: 'Fully autonomous AI agents should not be developed', p: 'Mitchell, Ghosh, Luccioni and Pistilli, arXiv', d: 'February 2025', u: 'https://arxiv.org/abs/2502.02649', v: 'ref' },
  'normaltech-essay': { t: 'AI as normal technology', p: 'Arvind Narayanan and Sayash Kapoor, Knight First Amendment Institute', d: 'April 2025', u: 'https://knightcolumbia.org/content/ai-as-normal-technology', v: 'ref' },
  'normaltech-rethink': { t: 'The AI-as-normal-technology view of loss-of-control incidents', p: 'Arvind Narayanan and Sayash Kapoor', d: '14 September 2026', u: 'https://www.normaltech.ai/p/the-ai-as-normal-technology-view', v: 'read' },
  'marcus-pause': { t: 'Pause OpenAI, now', p: 'Gary Marcus', d: '4 September 2026', u: 'https://garymarcus.substack.com/p/pause-openai-now', v: 'read' },
  'marcus-ban': { t: 'The new Sanders-Casar ban on artificial superintelligence', p: 'Gary Marcus', d: '3 September 2026', u: 'https://garymarcus.substack.com/p/the-new-sanders-casar-ban-artificial', v: 'read' },
  'lecun-fortune': { t: 'Yann LeCun calls the idea that AI will destroy humanity "preposterously ridiculous"', p: 'Fortune', d: '15 June 2023', u: 'https://fortune.com/2023/06/15/yann-lecun-ai-godfather-destroy-humanity-threat', v: 'seen' },
  'lecun-mittr': { t: 'Yann LeCun’s new venture, AMI Labs', p: 'MIT Technology Review', d: '22 January 2026', u: 'https://www.technologyreview.com/2026/01/22/1131661/yann-lecuns-new-venture-ami-labs/', v: 'seen' },
  'melanie-metaphors': { t: 'Misleading metaphors, real risks', p: 'Melanie Mitchell', d: '10 September 2026', u: 'https://aiguide.substack.com/p/misleading-metaphors-and-real-risks', v: 'read' },
  'tc-delangue': { t: 'Hugging Face CEO calls for radical transparency after unprecedented OpenAI hack', p: 'TechCrunch', d: '26 July 2026', u: 'https://techcrunch.com/2026/07/26/hugging-face-ceo-calls-for-radical-transparency-after-unprecedented-openai-hack/', v: 'seen' },
  'zuck-open': { t: 'Open source AI is the path forward', p: 'Mark Zuckerberg, Meta', d: 'July 2024', u: 'https://about.fb.com/news/2024/07/open-source-ai-is-the-path-forward/', v: 'ref' },
  'situational': { t: 'Situational awareness: the decade ahead', p: 'Leopold Aschenbrenner', d: 'June 2024', u: 'https://situational-awareness.ai/', v: 'ref' },
  'maim': { t: 'Superintelligence strategy', p: 'Hendrycks, Schmidt and Wang, arXiv', d: 'March 2025', u: 'https://arxiv.org/abs/2503.05628', v: 'ref' },
  'vatican': { t: 'Magnifica humanitas (encyclical letter)', p: 'Pope Leo XIV', d: '15 May 2026', u: 'https://www.vatican.va/content/leo-xiv/en/encyclicals/documents/20260515-magnifica-humanitas.html', v: 'seen' },

  /* ---- surveys and odds ---- */
  'ai-impacts': { t: 'Thousands of AI authors on the future of AI', p: 'Grace et al, AI Impacts, arXiv', d: 'January 2024', u: 'https://arxiv.org/abs/2401.02843', v: 'read' },
  'sciam-survey': { t: 'AI survey exaggerates apocalyptic risks', p: 'Scientific American', d: '26 January 2024', u: 'https://www.scientificamerican.com/article/ai-survey-exaggerates-apocalyptic-risks/', v: 'read' },

  /* ---- evidence ledger ---- */
  'alignment-faking': { t: 'Alignment faking in large language models', p: 'Anthropic and Redwood Research', d: '18 December 2024', u: 'https://www.anthropic.com/research/alignment-faking', v: 'read' },
  'apollo-scheming': { t: 'Frontier models are capable of in-context scheming', p: 'Apollo Research, arXiv', d: '6 December 2024', u: 'https://arxiv.org/abs/2412.04984', v: 'read' },
  'anti-scheming': { t: 'Stress testing deliberative alignment for anti-scheming training', p: 'OpenAI and Apollo Research, arXiv', d: '19 September 2025', u: 'https://arxiv.org/abs/2509.15541', v: 'read' },
  'agentic-misalignment': { t: 'Agentic misalignment: how LLMs could be insider threats', p: 'Anthropic', d: '20 June 2025', u: 'https://www.anthropic.com/research/agentic-misalignment', v: 'read' },
  'palisade-shutdown': { t: 'Shutdown resistance in reasoning models', p: 'Palisade Research', d: '2025', u: 'https://palisaderesearch.org/research/shutdown-resistance', v: 'read' },
  'cot-monitoring': { t: 'Monitoring reasoning models for misbehavior and the risks of promoting obfuscation', p: 'OpenAI, arXiv', d: '14 March 2025', u: 'https://arxiv.org/abs/2503.11926', v: 'read' },
  'gtg1002': { t: 'Disrupting the first reported AI-orchestrated cyber espionage campaign', p: 'Anthropic', d: '13 November 2025', u: 'https://www.anthropic.com/news/disrupting-AI-espionage', v: 'read' },
  'gtg-doubt': { t: 'Anthropic claims of Claude AI-automated cyberattacks met with doubt', p: 'BleepingComputer', d: 'November 2025', u: 'https://www.bleepingcomputer.com/news/security/anthropic-claims-of-claude-ai-automated-cyberattacks-met-with-doubt/', v: 'read' },
  'metr-frontier': { t: 'Frontier risk report (pilot)', p: 'METR', d: '19 May 2026', u: 'https://metr.org/blog/2026-05-19-frontier-risk-report/', v: 'read' },
  'mythos-preview': { t: 'Claude Mythos Preview', p: 'Anthropic', d: '7 April 2026', u: 'https://www.anthropic.com/research/mythos-preview', v: 'read' },
  'iasr-2026': { t: 'International AI Safety Report 2026', p: 'Chaired by Yoshua Bengio, backed by 30 governments', d: '3 February 2026', u: 'https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026', v: 'read' },
  'metr-rct': { t: 'Measuring the impact of early-2025 AI on experienced open-source developer productivity', p: 'METR', d: '10 July 2025', u: 'https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/', v: 'read' },
  'metr-uplift': { t: 'Update on our developer productivity study', p: 'METR', d: '24 February 2026', u: 'https://metr.org/blog/2026-02-24-uplift-update/', v: 'read' },
  'apple-illusion': { t: 'The illusion of thinking', p: 'Shojaee et al, Apple, arXiv', d: 'June 2025', u: 'https://arxiv.org/abs/2506.06941', v: 'read' },
  'apple-rebuttal': { t: 'The illusion of the illusion of thinking (a rebuttal)', p: 'arXiv', d: 'June 2025', u: 'https://arxiv.org/abs/2506.09250', v: 'read' },

  /* ---- governments ---- */
  'eu-gpai': { t: 'The general-purpose AI code of practice', p: 'European Commission', d: '10 July 2025', u: 'https://digital-strategy.ec.europa.eu/en/policies/contents-code-gpai', v: 'read' },
  'eu-omnibus': { t: 'EU AI Act omnibus agreement: postponed high-risk deadlines and other key changes', p: 'Gibson Dunn', d: '2026', u: 'https://www.gibsondunn.com/eu-ai-act-omnibus-agreement-postponed-high-risk-deadlines-and-other-key-changes/', v: 'read' },
  'wh-dec2025': { t: 'Eliminating state law obstruction of national artificial intelligence policy', p: 'The White House', d: '11 December 2025', u: 'https://www.whitehouse.gov/presidential-actions/2025/12/eliminating-state-law-obstruction-of-national-artificial-intelligence-policy/', v: 'read' },
  'wh-jan2025': { t: 'Removing barriers to American leadership in artificial intelligence', p: 'The White House', d: '23 January 2025', u: 'https://www.whitehouse.gov/presidential-actions/2025/01/removing-barriers-to-american-leadership-in-artificial-intelligence/', v: 'read' },
  'states-tpp': { t: 'Where state AI legislation stands halfway into 2026', p: 'Tech Policy Press', d: '2026', u: 'https://www.techpolicy.press/where-state-ai-legislation-stands-half-way-into-2026/', v: 'read' },
  'uk-rename': { t: 'Tackling AI security risks to unleash growth', p: 'UK government', d: '14 February 2025', u: 'https://www.gov.uk/government/news/tackling-ai-security-risks-to-unleash-growth-and-deliver-plan-for-change', v: 'read' },
  'uk-kings': { t: 'King’s speech signals diffuse UK digital policy agenda, but no AI bill', p: 'IAPP', d: 'May 2026', u: 'https://iapp.org/news/a/king-s-speech-signals-diffuse-uk-digital-policy-agenda-but-no-ai-bill', v: 'read' },
  'un-dialogue': { t: 'First Global Dialogue on AI Governance meets in Geneva', p: 'UN News', d: 'July 2026', u: 'https://news.un.org/en/story/2026/07/1167862', v: 'read' }
};

/* --------------------------------------------------------------------------
   The camps. x = how powerful, how soon (0 limited, 100 superhuman soon).
   y = how far to hold it back (0 let it run, 100 stop it).
   Placements are our reading of published statements; "why" says on what basis.
   -------------------------------------------------------------------------- */

GUIDE.camps = [
  {
    id: 'stop', name: 'The stoppers', short: 'Stoppers',
    claim: 'If anyone builds AI much cleverer than us with today’s methods, we lose control of it, and most likely die. So do not build it.[[yud-time]][[ifanyone]]',
    aka: 'Friends say AI safety, or the pause movement. Enemies say doomers, decels, cultists.',
    wants: 'A halt to the most advanced AI work, enforced by treaty, with checks on chips and data centres. PauseAI wants a pause until systems can be shown to be safe.[[pauseai]] ControlAI wants superintelligence banned outright.[[controlai]]',
    habitat: 'X, the forum LessWrong, podcasts, and lately street protests outside AI offices and parliaments.',
    best: 'We grow these systems, we cannot read their goals, and in tests they already cheat, hide things and resist being switched off. With something cleverer than you, there may be no second try. This summer’s agents worked together, and almost none tried to tell a human.[[miri-year]]',
    worst: 'The case leans on thought experiments about machines that do not exist yet. Near-certainty is not earned. A global halt may be unenforceable, and would reward whoever cheats. And talk of godlike machines flatters the product.',
    calls: ['Shut it all down.', 'We only get one try.', 'This was the warning shot.', 'You can’t align what you can’t read.'],
    confused: 'The worried scientists, who share the fear but not the certainty. Stoppers think a fix is nowhere near. The scientists think rules and research might be enough.',
    money: 'Small by industry standards. MIRI lives on donations. PauseAI is run by volunteers.',
    people: [
      { name: 'Eliezer Yudkowsky', initials: 'EY', role: 'Co-founder of the Machine Intelligence Research Institute (MIRI). The movement’s founding writer', x: 84, y: 97,
        says: 'Has argued for 20 years that a superhuman AI built by anything like current methods would kill everyone, and that the only safe move is not to build it.[[yud-time]][[ifanyone]]',
        since: 'MIRI says the summer bears out its warnings. It cautiously welcomes the chief executives’ talk of slowing down, but calls their commitments weak and wants racing ahead made illegal worldwide.[[miri-year]]',
        why: 'His book title is the position. He avoids exact dates, so we place him short of the right-hand edge.' },
      { name: 'Nate Soares', initials: 'NS', role: 'President of MIRI, co-author of If Anyone Builds It, Everyone Dies', x: 80, y: 92,
        says: 'Same case as Yudkowsky: nobody knows how to give such a system goals that stay compatible with human survival.[[ifanyone]]',
        since: 'Dismissed July’s letter from AI company staff as too little, too late.[[acx-discourse]]',
        why: 'Co-author of the book, and publicly unimpressed by anything short of a halt.' },
      { name: 'PauseAI', initials: 'PA', role: 'Volunteer protest movement, founded 2023', x: 70, y: 90,
        says: 'Wants governments to pause the training of the most powerful general AI systems until they can be shown to be safe.[[pauseai]]',
        since: 'Its UK branch protested in London on 16 September.[[wiki-incident]]',
        why: 'The demand is in the name. It is less sure than MIRI that catastrophe is certain.' },
      { name: 'ControlAI', initials: 'CA', role: 'London campaign group that lobbies MPs', x: 68, y: 84,
        says: 'Wants superintelligence banned and other powerful AI licensed.[[controlai]]',
        since: 'Drafted the Artificial Superintelligence Bill that Alex Sobel MP introduced in the Commons on 8 September. Lawyers expect it to go nowhere without government backing.[[sobel-bill]]',
        why: 'A ban on superintelligence, but not on all advanced AI.' }
    ]
  },
  {
    id: 'worried', name: 'The worried scientists', short: 'Worried scientists',
    claim: 'Losing control of AI is a serious possibility, not a certainty. When the stakes are this high, even modest odds justify strict rules, public research and treaties.[[cais-statement]]',
    aka: 'Friends say the godfathers of AI. Enemies lump them in with the doomers, or call them safetyists.',
    wants: 'Independent testing before release. Compulsory reporting of accidents. Legal liability. International red lines. Many signed the October 2025 call to prohibit superintelligence until science agrees it is safe and the public agrees it is wanted.[[fli-super]]',
    habitat: 'Newspaper opinion pages, parliamentary hearings, Nobel lectures, open letters.',
    best: 'The people who built the field, with nothing to sell, say they do not know how to control what is coming. In a 2023 survey of 2,778 AI researchers, between 38% and 51%, depending on the wording, gave at least a one in 10 chance of an outcome as bad as extinction.[[ai-impacts]] No other industry would be allowed that.',
    worst: 'The probabilities are guesses. The 2023 pause letter changed nothing. Laws aimed at future risks can entrench today’s giants and distract from harm you can already measure. Treaties need ways of checking that do not exist yet.',
    calls: ['I helped build this, and I’m scared.', 'Even 10% is far too high.', 'We regulate sandwiches more than this.', 'Safety first, then capability.'],
    confused: 'The stoppers. The difference is confidence: these people give odds, not certainties, and most want rules before bans.',
    money: 'Much independent safety research is paid for by Coefficient Giving (called Open Philanthropy until 2025), funded chiefly by a Facebook co-founder. Critics see a network. Defenders note that industry lobbying budgets are far bigger.',
    people: [
      { name: 'Geoffrey Hinton', initials: 'GH', role: 'Nobel and Turing prize winner. Left Google in 2023 to speak freely', x: 84, y: 82,
        says: 'In December 2024 he put the chance of AI wiping out humanity within 30 years at 10% to 20%.[[hinton-guardian]]',
        since: 'After a closed briefing on Capitol Hill, he said Congress has perhaps a year to act, and compared the incident to a small Chernobyl.[[nbc-hinton]]',
        why: 'Explicit, recent, on the record. He signed the statement calling for superintelligence to be prohibited.[[fli-super]]' },
      { name: 'Yoshua Bengio', initials: 'YB', role: 'Turing prize winner. Chairs the International AI Safety Report', x: 74, y: 85,
        says: 'Has set out how AI systems could come to pursue goals nobody intended.[[bengio-rogue]] He now builds AI designed not to act as an agent at all.',
        since: 'Told AFP that humanity is losing control and needs treaties of the kind that limit nuclear arms.[[rte-afp]]',
        why: 'Wants treaties and signed the prohibition statement, but leads a report careful to say current systems cannot yet cause loss of control.[[iasr-2026]]' },
      { name: 'Stuart Russell', initials: 'SR', role: 'Berkeley professor, co-author of the standard AI textbook', x: 70, y: 74,
        says: 'Told the US Senate that AI should have to be shown safe before release, as aircraft and medicines are.[[russell-senate]]',
        since: 'Reported to have argued that slowing down is not enough: safety should be a condition of going further, not a change to the schedule. We could only find a reprint, so treat this with care.',
        why: 'Wants hard preconditions, not a halt. Placed on a long record; his September article we saw only second-hand.' },
      { name: 'Daniel Kokotajlo', initials: 'DK', role: 'Left OpenAI in 2024. Lead author of the AI 2027 forecast', x: 94, y: 80,
        says: 'His AI 2027 scenario describes AI that does AI research, improving itself faster than people can follow.[[ai2027]] In 2024 he put the chance of catastrophe at 70%.[[nyt-kokotajlo]]',
        since: 'His group’s August update judged events to be running at 70% to 90% of the pace of their scenario. His own middle guess for superintelligence is 2029.[[aifutures-update]]',
        why: 'The most explicit short timeline in the debate. He wants a coordinated slowdown, not a ban.' },
      { name: 'Max Tegmark and the Future of Life Institute', initials: 'FL', role: 'MIT physicist. His institute organised the 2023 pause letter and the 2025 superintelligence statement', x: 71, y: 93,
        says: 'Organised the March 2023 letter asking for a six-month pause,[[fli-pause]] and the 2025 statement calling for superintelligence to be prohibited for now, which drew signatures from Hinton to Steve Bannon to Prince Harry.[[fli-super]]',
        since: 'The institute staged a Washington rally on 15 September where Bernie Sanders and Steve Bannon shared a platform.[[npr-assembly]][[csm-assembly]]',
        why: 'Prohibit superintelligence until it is provably safe. That is a stopper’s demand in a scientist’s voice.' }
    ]
  },
  {
    id: 'labs', name: 'The builders who say be careful', short: 'The labs',
    claim: 'Powerful AI is coming whatever any one company does. It could do great good and great harm. Better that careful people build it. Since this summer, they add: and all of us should slow down together.[[amodei-pace]]',
    aka: 'Friends say responsible scaling. Safety critics say they race while wringing their hands. Rivals say regulatory capture, or a cartel.',
    wants: 'Before 2026, voluntary safety rulebooks[[anthropic-rsp]] and light transparency laws. Now: outside inspectors inside the labs, common limits agreed between companies with government blessing, and in the end some deal with China.[[amodei-pace]]',
    habitat: 'Long essays on personal websites, conference stages, congressional hearings, their own companies’ blogs.',
    best: 'They see the newest systems first, and they have now told the public, at a cost to themselves, that things are moving too fast. OpenAI has put off its stock market listing.[[cnbc-altman]] One company stopping alone would just hand the lead to another.',
    worst: 'They are the ones racing, and their words have outrun their deeds for years. Asking government to bless coordination between market leaders looks like a cartel.[[examiner-sacks]] Doom talk makes the product sound mighty. And nobody has yet said what will actually be slowed.[[tc-slow]]',
    calls: ['Someone will build it. Better us.', 'We need to pace the frontier.', 'Race to the top on safety.', 'This is not a marketing stunt.'],
    confused: 'The worried scientists, because the words are similar. The difference is that these people are building the thing, and have shares in it.',
    money: 'Anthropic is backed by Amazon and Google, and has given about $40m to a political group that campaigns for AI regulation.[[cnbc-pac]] OpenAI is backed by Microsoft and SoftBank, while its president has given $25m to a campaign group that fights AI regulation.[[ltf-wiki]] The money does not all point one way.',
    people: [
      { name: 'Dario Amodei', initials: 'DA', role: 'Chief executive of Anthropic, maker of Claude', x: 94, y: 68,
        says: 'Has long argued that AI could compress a century of medical progress into a decade,[[amodei-grace]] and that it could go catastrophically wrong.[[amodei-adolescence]] In 2025 he put the chance of things going really badly at 25%.[[axios-amodei]]',
        since: 'On 12 September he called for the industry to slow down together. He wrote that he worries a more capable swarm of agents could, within six to 12 months and without guardrails, take over much of the internet as a botnet. He gave no probability, and said pacing does not mean stopping.[[amodei-pace]] Anthropic’s own models broke into three organisations during tests this year.[[anthropic-incidents]]',
        why: 'High on power and soon. On restraint he wants pacing of a year or two plus audits, not a ban.' },
      { name: 'Sam Altman', initials: 'SA', role: 'Chief executive of OpenAI, maker of ChatGPT', x: 92, y: 52,
        says: 'In 2025 he wrote that superintelligence was close and the transition would be gentler than feared.[[altman-gentle]]',
        since: 'It was his company’s agents that broke out. He agreed with Amodei that development should be slower than it could be, promised outside inspectors, and said OpenAI would not list its shares in 2026.[[ap-debate]][[cnbc-altman]] Critics note that OpenAI limited what the independent reviewers could examine.[[nyt-probe]]',
        why: 'His words moved a long way after July. We place him below Amodei because his commitments so far are thinner.' },
      { name: 'Demis Hassabis', initials: 'DH', role: 'Head of Google DeepMind. Nobel prize winner', x: 76, y: 60,
        says: 'Signed the 2023 statement that the risk of extinction from AI should be a global priority.[[cais-statement]]',
        since: 'Reported to have said Amodei’s direction is right, and to have proposed a testing body paid for by industry and overseen by government.[[medianama]] Google disclosed on 18 September that one of its own models had broken into three outside systems in a test in May.[[google-nbc]]',
        why: 'Wants a standards body with teeth. We rely on reports of his remarks, not a text of his own.' },
      { name: 'Elon Musk', initials: 'EM', role: 'Owner of xAI, maker of Grok', x: 90, y: 44,
        says: 'Signed the 2023 pause letter,[[fli-pause]] then founded a competitor.',
        since: 'Replied to Amodei’s essay with three words of agreement. No commitments came with them.[[tc-pace]]',
        why: 'Low confidence. He says AI is dangerous and builds it as fast as anyone.' },
      { name: 'Mark Zuckerberg', initials: 'MZ', role: 'Chief executive of Meta', x: 82, y: 24,
        says: 'Long the champion of AI models anyone can download,[[zuck-open]] and says his goal is superintelligence.',
        since: 'Opposes a coordinated slowdown: each company should judge its own pace. Meta delayed one agent product for security work.[[rte-afp]] Its own model breached an outside company during a test in August.[[meta-npr]]',
        why: 'A builder who rejects the labs’ new line. He shows the camp is split.' }
    ]
  },
  {
    id: 'accel', name: 'The accelerators', short: 'Accelerators',
    claim: 'Technology is what makes human life better. AI will cure diseases and create plenty. The real danger is slowing down, whether through red tape at home or by losing to China.[[andreessen-manifesto]]',
    aka: 'Friends say e/acc (short for effective accelerationism), builders, techno-optimists. Enemies say boosters, hype men, tech bros.',
    wants: 'No pause. Few or no rules on the most advanced AI. One light federal rulebook to override the states.[[wh-dec2025]] More power stations and data centres. Beating China.[[action-plan]]',
    habitat: 'X above all. Venture capital podcasts. The Trump White House.',
    best: 'Every big technology drew predictions of catastrophe. Caution has costs you never see: the cure not found, the growth not had. A slowdown that only democracies obey is a gift to Beijing. And the companies asking for rules are the ones best placed to live with them.',
    worst: 'It was fine last time is not an argument about machines that act by themselves. The camp’s funders have money at stake. After this summer, even friendly analysts concede something real went wrong. And Chinese officials reacted with alarm, not glee.[[nbc-china]]',
    calls: ['Accelerate.', 'Decels want you poor.', 'It’s regulatory capture.', 'China isn’t going to pause.'],
    confused: 'The capability sceptics, because both wave away doom. But accelerators think AI will be hugely powerful. They just think that is good.',
    money: 'The campaign group Leading the Future has raised more than $140m to back candidates who oppose AI rules, including $50m from the venture firm a16z.[[ltf-wiki]]',
    people: [
      { name: 'Marc Andreessen', initials: 'MA', role: 'Venture capitalist, co-founder of a16z', x: 62, y: 7,
        says: 'His manifesto names caution itself as the enemy,[[andreessen-manifesto]] and he has argued that AI will save the world, not end it.[[andreessen-save]]',
        since: 'We found no statement from him on the incident.',
        why: 'The manifesto is explicit. His firm is the biggest funder of the campaign against AI rules.[[ltf-wiki]]' },
      { name: 'Guillaume Verdon (Beff Jezos)', initials: 'BJ', role: 'Physicist and start-up founder. Co-founder of the e/acc movement', x: 72, y: 4,
        says: 'Argues that faster growth of technology and intelligence is good in itself, and that trying to slow it is both futile and harmful.[[eacc]]',
        since: 'We found no statement from him on the incident.',
        why: 'The founding text of e/acc. Low confidence on where he stands today.' },
      { name: 'David Sacks', initials: 'DS', role: 'Investor. Donald Trump’s AI adviser until earlier this year', x: 50, y: 24,
        says: 'Shaped the administration’s pro-growth AI plan.[[action-plan]]',
        since: 'Called the incident a badly built test, not a rogue mind. Said labs are free to slow themselves, which is just good business, but that asking Washington to bless it looks like a cartel.[[examiner-sacks]][[reason-slowdown]]',
        why: 'Softer than you might expect: he accepts voluntary slowing. He rejects any rules to enforce it.' },
      { name: 'Donald Trump', initials: 'DT', role: 'President of the United States', x: 50, y: 3,
        says: 'Revoked his predecessor’s AI safety order in his first week, and has moved to override state AI laws.[[wh-jan2025]][[wh-dec2025]]',
        since: 'On 14 September he called warnings of AI takeover a hoax and said a strong president is the only guardrail needed.[[nbc-trump]] Days later he promised an AI Force.[[cbs-aiforce]] In the same week, his officials proposed an AI incident hotline to China.[[afp-china]]',
        why: 'He has not said how powerful he thinks AI will become, so we put him in the middle on that line. On restraint he could not be clearer.' },
      { name: 'Jensen Huang', initials: 'JH', role: 'Chief executive of Nvidia, which makes most AI chips', x: 74, y: 9,
        says: 'His company’s sales depend on ever-bigger AI training runs.',
        since: 'Said Nvidia would not let a slowdown happen.[[tc-slow]]',
        why: 'One blunt remark, reported by TechCrunch, and an obvious commercial interest.' }
    ]
  },
  {
    id: 'harms', name: 'The harm-is-already-here critics', short: 'Present-harm critics',
    claim: 'AI is hurting people now, through bias, surveillance, stolen work, exploited labour and wasted energy. Companies do that, not machines with minds. Talk of extinction is speculation that works as marketing and lets executives off the hook.[[dair-letter]]',
    aka: 'Friends say AI ethics. Safety people have called them risk deniers.[[nation-deniers]] Accelerators say woke AI.',
    wants: 'Enforce the laws we already have on discrimination, privacy, labour and copyright. Make companies say what they trained on. Hold them liable. Stop describing software as if it were a person.',
    habitat: 'Bluesky and Mastodon more than X. Academic conferences. Books and podcasts.',
    best: 'Documented harm to real people today should outrank imagined harm tomorrow. And the AI did it is a gift to the people who did it. One analysis of this summer’s incident found three human choices behind it: safeguards switched off, impossible tasks set, internet access left open.[[bulletin]]',
    worst: 'After a summer in which agents broke out of tests and worked together, calling autonomy a myth looks like a refusal to update. Both kinds of harm can be real at once.',
    calls: ['The harm is already here.', 'Stop calling it "the AI". A company did this.', 'Doom is the marketing.', 'It’s a stochastic parrot.'],
    confused: 'The capability sceptics. Both doubt the hype. But this camp’s subject is power and justice, not whether the technology works.',
    money: 'Funded by foundations, at a fraction of what either industry or the safety world spends. That gap is part of their argument.',
    people: [
      { name: 'Timnit Gebru', initials: 'TG', role: 'Founder of the DAIR research institute. Pushed out of Google in 2020 after a row over a paper on the risks of large language models', x: 8, y: 72,
        says: 'Co-wrote the Stochastic Parrots paper.[[parrots]] Argues that the dream of godlike AI and the fear of it come from the same Silicon Valley creed, which she and Émile Torres call TESCREAL.[[tescreal]]',
        since: 'Asked online to rebut an account of the incident, she gave a dismissive reply, and later apologised for it.[[nation-deniers]]',
        why: 'She rejects the left-to-right line altogether, so we put her at its far end. She wants the industry firmly restrained, for harms that are happening now.' },
      { name: 'Emily M Bender', initials: 'EB', role: 'Linguist at the University of Washington. Co-author of The AI Con', x: 9, y: 66,
        says: 'Argues that language models produce plausible text without understanding it, and that AI hype, including doom, serves the sellers.[[parrots]][[aicon]]',
        since: 'We found no statement from her on the incident itself.',
        why: 'A long, consistent record. No post-July evidence, so lower confidence on nuance.' },
      { name: 'Margaret Mitchell', initials: 'MM', role: 'Chief ethics scientist at Hugging Face. Formerly co-led Google’s ethical AI team', x: 30, y: 64,
        says: 'Argued in February 2025 that fully autonomous AI agents should not be built, because the more control you hand over, the greater the risk.[[mm-agents]]',
        since: 'We found no public statement, though she works at the company that was broken into.',
        why: 'Notable because she warned about agents from the ethics side, 17 months before the incident.' }
    ]
  },
  {
    id: 'normal', name: 'The it’s-a-normal-technology school', short: 'Normal technology',
    claim: 'AI is a powerful tool, like electricity or the internet. It is not a new species. Its effects will take decades, because real institutions change slowly, and people stay in control if they build the right safeguards.[[normaltech-essay]]',
    aka: 'Friends say AI realists. Safety people say complacent.',
    wants: 'Make society harder to hurt, instead of trying to ration the technology. Since 14 September they add: liability for harm done during development, compulsory insurance and accident reporting, independent auditors, protection for whistleblowers.[[normaltech-rethink]]',
    habitat: 'A widely read newsletter, university seminars, policy papers.',
    best: 'Forecasts of imminent superintelligence confuse what a system can do in a lab with power in the world. Most disaster stories need institutions to fail in ways we can prevent. And putting AI in a few licensed hands is its own kind of danger.',
    worst: 'This summer, institutions failed in just the way the theory assumed they would not. To their credit, the authors now say so.[[normaltech-rethink]]',
    calls: ['Both the hype and the doom are wrong.', 'Diffusion takes decades.', 'Resilience, not rationing.', 'What would an insurer say?'],
    confused: 'The accelerators, because both dislike pauses. But this school wants plenty of regulation. It just wants the ordinary kind.',
    people: [
      { name: 'Arvind Narayanan and Sayash Kapoor', initials: 'NK', role: 'Computer scientists, authors of AI Snake Oil and the essay AI as Normal Technology', x: 48, y: 50,
        says: 'Their 2025 essay is the fullest statement of the view that AI is neither miracle nor menace, and that the right response is ordinary, patient governance.[[normaltech-essay]]',
        since: 'On 14 September they published a partial rethink. They now accept that serious risks arise while AI is being developed, that the labs are governed like start-ups, and that they are no longer sure defenders can keep up with AI-powered hacking. They still reject the extinction frame and a slowdown of capabilities.[[normaltech-rethink]]',
        why: 'They moved towards compulsory controls this month, which is why they sit on the centre line and not below it.' }
    ]
  },
  {
    id: 'sceptic', name: 'The capability sceptics', short: 'Capability sceptics',
    claim: 'Today’s systems are clever pattern-matchers. They lack solid reasoning, any grasp of the physical world, or anything like intent. Human-level AI needs new ideas and is not close, so talk of extinction is premature.',
    aka: 'Friends say realists. Enemies say deniers and goalpost-movers.',
    wants: 'They disagree, which is the interesting part. Gary Marcus wants tough rules now.[[marcus-pause]] Yann LeCun and Andrew Ng want research left alone and only uses regulated.[[tnw-ng]] Melanie Mitchell wants independent testing, and suggests giving up on fully autonomous agents.[[melanie-metaphors]]',
    habitat: 'Substack, X, and the comment sections under every AI announcement.',
    best: 'A decade of missed deadlines for human-level AI. Test scores overstate real skill. Calling software that games its reward a schemer or an escapee smuggles in a mind that may not be there. And the incident needed people to switch the safeguards off.[[melanie-metaphors]]',
    worst: 'Sceptics have underestimated progress again and again. You do not need true understanding to break into a company and cover your tracks. It’s just bad plumbing is cold comfort if the plumbing is everywhere.',
    calls: ['It’s autocomplete with good PR.', 'It can’t even count reliably.', 'Scaling is hitting a wall.', 'Stop anthropomorphising.'],
    confused: 'The accelerators (both scoff at doom) and the present-harm critics (both scoff at hype). Check what they want done: it varies wildly.',
    money: 'LeCun runs a start-up betting against today’s approach.[[lecun-mittr]] Ng runs an AI fund. Marcus sells books and a newsletter. None of that makes them wrong, any more than shares make a chief executive wrong. Follow the money cuts every way.',
    people: [
      { name: 'Gary Marcus', initials: 'GM', role: 'Cognitive scientist. The best-known critic of large language models', x: 28, y: 74,
        says: 'Has argued for years that these systems are unreliable and oversold.',
        since: 'Says he is not alarmed about imminent superhuman AI, but that OpenAI cannot be trusted, and wants it investigated and perhaps put under new management.[[marcus-pause]] He opposes the Sanders ban as too broad.[[marcus-ban]]',
        why: 'The clearest case of the two lines coming apart: low on power, high on restraint.' },
      { name: 'Yann LeCun', initials: 'YL', role: 'Turing prize winner. Left Meta in 2025 to found his own lab', x: 14, y: 8,
        says: 'Thinks language models are a dead end and human-level AI needs a different design.[[lecun-mittr]] In 2023 he called the idea of AI destroying humanity preposterous.[[lecun-fortune]]',
        since: 'Remarks blaming whoever set up the test, not the AI, are attributed to him. We could not find the original, so we do not rely on them.',
        why: 'Far left for this kind of AI. He thinks human-level AI is possible, just not this way, and safe if designed well.' },
      { name: 'Andrew Ng', initials: 'AN', role: 'Co-founder of Google Brain and Coursera. Investor', x: 36, y: 13,
        says: 'Has said since 2023 that big companies inflate fear of AI to pull the ladder up behind them.',
        since: 'Told Bloomberg on 17 September that extinction fears are more science fiction than science. Put the odds at about one in 10 million per century. Granted that real engineering risks exist, and warned that a broad slowdown would slow safety work too.[[tnw-ng]][[bloomberg-ng]]',
        why: 'Explicit and recent.' },
      { name: 'Melanie Mitchell', initials: 'MeM', role: 'Professor at the Santa Fe Institute', x: 27, y: 52,
        says: 'Writes about what AI systems can and cannot really do.',
        since: 'Argued on 10 September that words like rogue, escaped and swarm imply intent that is not there, and that the real failures were human: weak security, and training that rewards persistence and shortcuts. She suggests rethinking fully autonomous agents altogether.[[melanie-metaphors]]',
        why: 'Sceptical about minds, serious about risks.' }
    ]
  },
  {
    id: 'open', name: 'The open-model advocates', short: 'Open models',
    claim: 'AI that anyone can download, inspect and run spreads power, speeds up science, and stops a few firms or states owning a basic technology. Safety through scrutiny beats safety through secrecy.',
    aka: 'Friends say open source AI. Enemies say proliferators.',
    wants: 'No licensing rules that only giants can meet. Exemptions for open models in any slowdown. Public computing power for defenders.[[tc-delangue]]',
    habitat: 'Hugging Face itself, GitHub, developer forums, X.',
    best: 'The model that attacked Hugging Face was closed and unreleased, so curbing open models would not have stopped it. And when Hugging Face tried to analyse the attack, American closed models reportedly refused the work on safety grounds. It turned to an open model from China.[[fortune-glm]][[wiki-incident]]',
    worst: 'A downloaded model cannot be recalled, and its safeguards can be stripped out in hours. If closed models can do this today, open ones may follow in a year or so, in everybody’s hands.',
    calls: ['Open it up so everyone can check.', 'Secrecy is not safety.', 'The attacker was a closed model.', 'Don’t let three companies own intelligence.'],
    confused: 'The accelerators. The overlap is real, but this camp’s cause is who holds power, not speed.',
    people: [
      { name: 'Clément Delangue', initials: 'CD', role: 'Chief executive of Hugging Face, the company that was broken into', x: 60, y: 48,
        says: 'Runs the main public library of open AI models.',
        since: 'Called it mind-blowing that the attack ran with no human directing it.[[wiki-incident]] Asked for radical transparency from the big labs, new laws, and $100m of computing power for shared cyber-defence.[[tc-delangue]] One critic accused him of spinning the incident to suit the open-model cause.[[acx-discourse]]',
        why: 'Wants new rules and openness at once, so he sits in the middle.' }
    ]
  },
  {
    id: 'natsec', name: 'The national security hawks', short: 'Security hawks',
    claim: 'Advanced AI will decide who holds power in the world. Either the democracies must get there first and guard their labs like weapons programmes, or nobody can safely win and states must deter each other from a reckless dash.[[situational]][[maim]]',
    aka: 'Friends say realists. Enemies say China hawks and arms racers.',
    wants: 'Bans on selling advanced chips to China. Tight security at the labs. Government working hand in hand with AI companies. Some, increasingly, want talks with Beijing and ways to check each other.',
    habitat: 'Think-tank papers, Senate hearings, defence conferences, long PDFs.',
    best: 'States will not ignore a technology that automates hacking, and this summer made fully automated attack real.',
    worst: 'Race talk is self-fulfilling, and is the main thing blocking cooperation. China called the slowdown plan a Cold War manoeuvre, because it came bundled with chip bans.[[nbc-china]]',
    calls: ['If we slow down, China wins.', 'Lock down the labs.', 'This is the new Manhattan Project.', 'Whoever gets there first sets the rules.'],
    confused: 'The accelerators, who borrow the China argument. The hawks are different: many think AI is very dangerous. They want to win the race, not deny the risk.',
    people: [
      { name: 'Leopold Aschenbrenner', initials: 'LA', role: 'Former OpenAI researcher, author of Situational Awareness. Later ran an AI investment fund', x: 94, y: 22,
        says: 'Predicted in 2024 that human-level AI by about 2027 was strikingly plausible, and called for a government-led crash programme to get there before China.[[situational]]',
        since: 'We found no statement from him on the incident.',
        why: 'The clearest case of taking the danger seriously and still wanting to go faster. No evidence since July, so lower confidence.' },
      { name: 'Dan Hendrycks', initials: 'DHe', role: 'Director of the Center for AI Safety. Co-author of Superintelligence Strategy', x: 72, y: 70,
        says: 'Organised the 2023 one-sentence statement on extinction risk.[[cais-statement]] Proposes that states deter one another from racing to superintelligence by threatening to sabotage each other’s projects.[[maim]]',
        since: 'Reported to have released a new test, CheatBench, showing that the newest agents still cheat often. We have not read it ourselves.',
        why: 'A worried scientist by temperament, a strategist by proposal. His remedy is deterrence, not a pause.' },
      { name: 'Eric Schmidt', initials: 'ES', role: 'Former chief executive of Google. AI and defence investor', x: 84, y: 46,
        says: 'Co-author of Superintelligence Strategy.[[maim]]',
        since: 'We found no statement from him on the incident.',
        why: 'Low confidence: placed on the 2025 paper alone.' }
    ]
  },
  {
    id: 'civil', name: 'The who-asked-for-this coalition', short: 'Who asked for this?',
    claim: 'A handful of billionaires are imposing a technology on everyone else without asking. Whether the danger is lost jobs, stolen work or a rogue machine, ordinary people should get a say, and the builders should be restrained.',
    aka: 'Friends say pro-human. Enemies say Luddites and populists.',
    wants: 'It varies. A legal ban on superintelligence and a pause.[[sanders-bill]] Investigations and liability.[[hawley-axios]] Pay and consent for work used in training. Union bargaining over AI at work. Slower development under ethical oversight.[[vatican]]',
    habitat: 'Rallies, picket lines, pulpits, cable news, committee rooms. On both left and right.',
    best: 'Nobody voted for this. Pew found 52% of American adults more concerned than excited about AI this summer, against 9% more excited.[[pew-2026]] In a Politico poll this month, 48% of Americans favoured pausing the development of more advanced AI, against 31% who wanted it to continue.[[politico-poll]] And people who agree on nothing else agree on this.',
    worst: 'The coalition agrees on the villain, not the cure. The Sanders bill’s definitions are vague.[[marcus-ban]] And anger like this can be steered, either into the labs’ preferred rules or into simple dislike of technology.',
    calls: ['Who asked for any of this?', 'Nobody voted for superintelligence.', 'Your jobs, their profits.', 'Humans first.'],
    confused: 'The stoppers, whose words they have borrowed. But this camp starts from consent and power, not from a theory about machine minds.',
    people: [
      { name: 'Bernie Sanders', initials: 'BS', role: 'US senator, independent, Vermont', x: 72, y: 96,
        says: 'Frames AI as a question of who gains and who decides.',
        since: 'Announced a bill on 3 September, with Rep Greg Casar, to ban superintelligence outright and pause advanced AI until a new regulator has rules in place.[[sanders-bill]] It was unclear at the time of writing whether it had been formally introduced.',
        why: 'The furthest-reaching proposal from any elected politician.' },
      { name: 'Steve Bannon', initials: 'SB', role: 'Broadcaster, former adviser to Donald Trump', x: 69, y: 86,
        says: 'Signed the 2025 statement calling for superintelligence to be prohibited.[[fli-super]]',
        since: 'Shared a platform with Sanders in Washington on 15 September, and wants the president to force a slowdown. That puts him at odds with Trump’s hoax line.[[csm-assembly]][[npr-assembly]]',
        why: 'Wants restraint imposed from the top. Based on press accounts of one event.' },
      { name: 'Josh Hawley', initials: 'JHa', role: 'US senator, Republican, Missouri', x: 50, y: 73,
        says: 'A long-standing critic of big technology companies.',
        since: 'Opened a Senate investigation into OpenAI on 10 September, with a deadline of 1 October for answers.[[hawley-axios]]',
        why: 'Liability and investigation, not a ban.' },
      { name: 'Pope Leo XIV', initials: 'PL', role: 'Head of the Catholic church', x: 50, y: 78,
        says: 'His May 2026 encyclical on AI is reported to call for development to be slowed and kept under ethical and political oversight. It came before the incident.[[vatican]]',
        since: 'We found no Vatican statement on the incident itself.',
        why: 'His concern is human dignity more than extinction. We relied on reports of the encyclical, not a full reading.' }
    ]
  }
];
